# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     image: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/midara-backend:latest
#     container_name: midara-backend
#     restart: unless-stopped
#     env_file:
#       - ./backend/.env
#     ports:
#       - "5000:5000"
#     depends_on:
#       - frontend
#     networks:
#       - midara-network

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     image: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/midara-frontend:latest
#     container_name: midara-frontend
#     restart: unless-stopped
#     env_file:
#       - ./frontend/.env
#     ports:
#       - "3000:3000"
#     networks:
#       - midara-network

# networks:
#   midara-network:
#     driver: bridge

services:
  backend:
    image: 092171113246.dkr.ecr.us-east-1.amazonaws.com/midara/backend:latest
    container_name: midara-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    networks:
      - midara-network

  frontend:
    image: 092171113246.dkr.ecr.us-east-1.amazonaws.com/midara/frontend:latest
    container_name: midara-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    networks:
      - midara-network

  nginx:
    build: ./nginx
    container_name: midara-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs # Certificados SSL gerenciados pelo Certbot
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot-webroot:/var/www/certbot
    depends_on:
      - backend
      - frontend
    networks:
      - midara-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    command: >
      certbot certonly --webroot -w /var/www/certbot -d midara.ink -d www.midara.ink --email midara.h@protonmail.com --agree-tos --non-interactive
    restart: "no"
    networks:
      - midara-network

networks:
  midara-network:
    driver: bridge
